version: '3.8'

services:
  db:
    image: mariadb:latest
    volumes:
      - ./docker/volumes/db_data:/var/lib/mysql
    restart: always
    container_name: jsl-skills__db
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: wordpress
      MARIADB_USER: user
      MARIADB_PASSWORD: password

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8080:80"
    restart: always
    container_name: jsl-skills__wp
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
    volumes:
      - ./docker/php.ini:/usr/local/etc/php/php.ini
      - ./plugins/jsl-gutenberg-blocks:/var/www/html/wp-content/plugins/jsl-gutenberg-blocks
      - ./plugins/jsl-newsletter-post-type:/var/www/html/wp-content/plugins/jsl-newsletter-post-type
      - ./docker/volumes/wp-content/plugins:/var/www/html/wp-content/plugins
      - ./docker/volumes/wp-content/uploads:/var/www/html/wp-content/uploads
      - ./themes/jsltheme:/var/www/html/wp-content/themes/jsltheme
volumes:
    db_data: {}
